project/server/models.py
# project/server/models.py


import datetime

from project.server import app, db, bcrypt

class LatexFile(db.Model):

  __tablename__ = "latex_files"

  uuid = db.Column(db.String(100), primary_key=True)
  text = db.Column(db.Text, nullable=False)

  def __init__(self, uuid, text):
    self.uuid = uuid
    self.text = text

class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, email, password, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, app.config.get('BCRYPT_LOG_ROUNDS')
        )
        self.registered_on = datetime.datetime.now()
        self.admin = admin

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User {0}>'.format(self.email)

project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    email = StringField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(FlaskForm):
    email = StringField(
        'Email Address',
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40)
        ]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

project/__init__.py
# project/__init__.py

project/server/__init__.py
# project/server/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy


################
#### config ####
################

app = Flask(
    __name__,
    template_folder='../client/templates',
    static_folder='../client/static'
)


app_settings = os.getenv('APP_SETTINGS', 'project.server.config.ProductionConfig')
app.config.from_object(app_settings)

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)


###################
### blueprints ####
###################

from project.server.user.views import user_blueprint
from project.server.main.views import main_blueprint
app.register_blueprint(user_blueprint)
app.register_blueprint(main_blueprint)


###################
### flask-login ####
###################

from project.server.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = 'danger'


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/server/main/__init__.py
# project/server/main/__init__.py

project/server/main/views.py
# project/server/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, request
import json
from .handlers import handle_latex_text, handle_latex_file

################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")


@main_blueprint.route("/format/", methods=["POST"])
def format_code():
    #TODO: be defensive here. The front end is a mess so I have to check stuff here
    # TODO: get options from the client side, build a JSON very alike to this one
    options = {}
    options["isTabs"] = False

    if request.form["spaces_or_tabs"] == "tabs":
      options["isTabs"] = True

    options["number_of"] = request.form["number_of"]

    formatted_latex = handle_latex_text(request.form["latex_data"], options)
    return formatted_latex

@main_blueprint.route("/formatfile/", methods=["POST"])
def format_file():
    latex_file = request.files['file']
    options = {}
    options["isTabs"] = False

    if request.form["spaces_or_tabs"] == "tabs":
      options["isTabs"] = True

    options["number_of"] = request.form["number_of"]

    formatted_latex = handle_latex_file(latex_file, options)

    return formatted_latex

project/server/user/__init__.py
# project/server/user/__init__.py

project/server/user/views.py
# project/server/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User
from project.server.user.forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("user.members"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.members'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

project/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Latex formatter{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/client/templates/footer.html
<footer>
  <div class="container">
    <small>
      <span>© Albert Thompson</span>
    </small>
  </div>
</footer>

project/client/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Latex formatter</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          {% if current_user.is_authenticated %}
           <li><a href="{{ url_for('user.members') }}">Members</a></li>
          {% endif %}
        </ul>
        <!--
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>
          {% endif %}
        </ul>
        -->
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>

project/client/templates/main/about.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <h1>About</h1>
  </div>
</div>

{% endblock %}

project/client/templates/main/home.html
{% extends "_base.html" %} {% block content %}

<div class="body-content">
    <div class="row">
        <div class="col-md-8">
            <h1>Welcome!</h1>
            <hr />
            <p>
                Latex formatter is a formatter for your latex code. Enter your code in the text area below and click on the button <strong>Format</strong>, if you prefer to upload your file, just click on the button <strong>choose a file </strong> and click on the button <strong>Format</strong>.
            </p>

            <p>
                Insert your code below or upload a latex file
                <form enctype="multipart/form-data" method="post" name="fileinfo">
                    <input class="btn btn-default btn-file" type="file" name="file" id="file" style="float:left; margin-right: 10px;">
                    <input class="btn btn-primary" type="submit" value="Upload" />
                </form>
            </p>
            <textarea class="form-control" rows="15" id="latexcode"></textarea>
            <button type="button" id="formatbutton" class="btn btn-primary">Format</button>
        </div>
        <div class="col-md-4">
            <h1> Formatting Options </h1>
            <hr />
            <div class="form-group">
                <select class="form-control" id="numberof" name="numberof">
                    <option value="2">2</option>
                    <option value="4">4</option>
                    <option value="6">6</option>
                    <option value="8">8</option>
                </select>
            </div>
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-primary active">
                    <input type="radio" name="options" value="spaces" id="spaces" autocomplete="off" checked> Spaces
                </label>
                <label class="btn btn-primary">
                    <input type="radio" name="options" value="tabs" id="tabs" autocomplete="off"> Tabs
                </label>
            </div>
        </div>
        <div class="col-md-8" id="result"></div>
    </div>
</div>

{% endblock %}

project/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please login</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </div>

  </form>


{% endblock content %}

project/client/templates/user/members.html
{% extends "_base.html" %}
{% block content %}
  <h1>Welcome, <em>{{ current_user.email }}</em>!</h1>
  <h3>This is the members-only page.</h3>
{% endblock %}

project/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please Register</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>

    </div>

  </form>


{% endblock content %}